grid:
  image: docker-proxy.kontur.host/node:20
  tags:
    - idevops
  stage: test
  parallel:
    matrix:
      - FIXTURE:
          - esm
          - playwright-grid
          - vite
          - vite-sb8
          - webpack
          - webpack-sb8
          - yarn-pnp
  script:
   - cd $FIXTURE
   - yarn
   - yarn storybook build
   - yarn http-server ./storybook-static -p 6006 -s &
   - yarn creevey --debug
  artifacts:
    paths:
      - $FIXTURE/report

local:
  image: docker-proxy.kontur.host/node:20
  tags:
    - idevops
  stage: test
  variables:
    DOCKER: true
  script:
   - cd playwright-docker
   - yarn
   - yarn dlx playwright@1.50.1 install --with-deps chromium
   - yarn storybook build
   - yarn http-server ./storybook-static -p 6006 -s &
   - yarn creevey --debug
  artifacts:
    paths:
      - playwright-docker/report

docker:
  image: docker-proxy.kontur.host/node:20
  tags:
    - docker-build
  stage: test
  script:
    - cd playwright-docker
    - yarn
    - yarn storybook build
    - yarn http-server ./storybook-static -p 6006 -s &
    - yarn creevey --debug
  artifacts:
    paths:
      - playwright-docker/report
